<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LPCAIQ1132" failures="0" tests="2" name="Cucumber_TestRunner.LoginRunnerNegative" time="13.241" errors="0" timestamp="2023-01-01T12:09:15 EET" skipped="0">
  <testcase classname="Cucumber_TestRunner.LoginRunnerNegative" name="runScenario" time="5.838"/>
  <system-out>
    <![CDATA[The ‘Username’ used for this test run is:>> []
The ‘Password’ used for this test run is:>> []
All fields error message were displayed and has been asserted || Test case passed]]>
  </system-out>
  <testcase classname="Cucumber_TestRunner.LoginRunnerNegative" name="runScenario" time="7.403"/>
  <system-out>
    <![CDATA[The ‘Username’ used for this test run is:>> [admin123]
The ‘Password’ used for this test run is:>> [Admin]
The invalid credentials error message was displayed and has been asserted || Test case passed]]>
  </system-out>
</testsuite> <!-- Cucumber_TestRunner.LoginRunnerNegative -->
